name = "rag"
main = "src/index.ts"
compatibility_date = "2024-10-28"

[ai]
binding = "AI"

[vars]
ENABLE_TEXT_SPLITTING = true

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DATABASE"
database_name = "rag-notes"
database_id = "be7f23a9-3f53-4fc5-8e0e-41a5341824ba"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "rag-notes-index"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"
